-- W7 Box League — LAUNCH PACK (regenerated 4 Sep 2026, 87 teams / 174 players)
-- Paste into the Supabase SQL editor and run top to bottom. Safe to re-run (it rebuilds the teams).
-- No matches or scores exist yet, so deleting box_teams loses nothing.

-- ── PART 0: the boxes (delete + reinsert, from scripts/build_box_seed.py) ──
-- Provisional Autumn/Winter Padel Box League boxes.
-- Generated by scripts/build_box_seed.py from the Playtomic entrant list.
-- Boxes are by COMBINED Playtomic rating and are provisional until entry closes.
begin;
delete from public.box_teams;
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (1, 1, 'Shane Donohoe & Dylan Orr', 'Shane Donohoe', 'Dylan Orr', 4.51, 4.13);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (1, 2, 'Davy O''Sullivan & David Hennebry', 'Davy O''Sullivan', 'David Hennebry', 4.53, 3.51);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (1, 3, 'J.P. Comerford & Conor Ruttledge', 'J.P. Comerford', 'Conor Ruttledge', 3.09, 4.49);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (1, 4, 'Tomas Morrissey & Brian Cornyn', 'Tomas Morrissey', 'Brian Cornyn', 3.51, 3.8);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (1, 5, 'David Deady & Rob Lucy', 'David Deady', 'Rob Lucy', 2.73, 4.34);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (2, 1, 'James Connolly & Michael Connolly', 'James Connolly', 'Michael Connolly', 2.81, 4.04);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (2, 2, 'Mike Shanahan & Greg Shine', 'Mike Shanahan', 'Greg Shine', 3.52, 3.24);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (2, 3, 'Dean Noble & Chris Ffrench', 'Dean Noble', 'Chris Ffrench', 3.72, 2.85);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (2, 4, 'Dylan Furlong & Jack Furlong', 'Dylan Furlong', 'Jack Furlong', 3.32, 3.2);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (2, 5, 'Antonio Loboschi & Sahil Kaistha', 'Antonio Loboschi', 'Sahil Kaistha', 2.79, 3.61);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (3, 1, 'Matthew & Nathan Condell', 'Matthew', 'Nathan Condell', 3.47, 2.63);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (3, 2, 'Sean Leonard & Dylan Frazer', 'Sean Leonard', 'Dylan Frazer', 2.48, 3.39);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (3, 3, 'Ingvard Hanssen & Oisin Breen', 'Ingvard Hanssen', 'Oisin Breen', 3.87, 1.49);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (3, 4, 'Ciara Kavanagh & Rory Fahey', 'Ciara Kavanagh', 'Rory Fahey', 1.47, 3.69);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (3, 5, 'Ronel Pickford & Dawn B', 'Ronel Pickford', 'Dawn B', 2.6, 2.43);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (4, 1, 'Desmond Martin & Dave Smyth', 'Desmond Martin', 'Dave Smyth', 2.7, 2.16);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (4, 2, 'Shane Devlin & Karl Earls', 'Shane Devlin', 'Karl Earls', 2.8, 2.04);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (4, 3, 'Mark Banim & Anton Burihhin', 'Mark Banim', 'Anton Burihhin', 2.6, 2.17);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (4, 4, 'Kieran Fraser & Ana J', 'Kieran Fraser', 'Ana J', 2.8, 1.88);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (4, 5, 'Shaun Humby & Thomas McKeon', 'Shaun Humby', 'Thomas McKeon', 2.3, 2.32);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (5, 1, 'Tom Maguire & Brian O''Sullivan', 'Tom Maguire', 'Brian O''Sullivan', 2.12, 2.44);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (5, 2, 'Lee Fitzpatrick & Mo Dunne', 'Lee Fitzpatrick', 'Mo Dunne', 2.33, 2.2);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (5, 3, 'Kayleigh Sullivan & Leanne S', 'Kayleigh Sullivan', 'Leanne S', 2.18, 2.29);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (5, 4, 'Aisling O''Brien & Patrick Kennelly', 'Aisling O''Brien', 'Patrick Kennelly', 1.9, 2.56);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (5, 5, 'Charles Lee & Cami Ammirevole', 'Charles Lee', 'Cami Ammirevole', 3.06, 1.37);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (6, 1, 'Karol Stankiewicz & Sath', 'Karol Stankiewicz', 'Sath', 1.78, 2.48);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (6, 2, 'Gabriel Uribe & Aron Souto', 'Gabriel Uribe', 'Aron Souto', 2.23, 2.01);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (6, 3, 'Callum Smale & Ryan Tolan', 'Callum Smale', 'Ryan Tolan', 2.64, 1.57);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (6, 4, 'Keefe Lang & Chris Lang', 'Keefe Lang', 'Chris Lang', 2.68, 1.51);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (6, 5, 'Cillian Williams & Ava Williams', 'Cillian Williams', 'Ava Williams', 2.53, 1.66);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (7, 1, 'John D & Sam Harte', 'John D', 'Sam Harte', 2.11, 2.02);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (7, 2, 'Toby Wuyts & Jack Dunn', 'Toby Wuyts', 'Jack Dunn', 2.39, 1.73);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (7, 3, 'Oussama Kenouche & Jack Colaluca', 'Oussama Kenouche', 'Jack Colaluca', 2.36, 1.69);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (7, 4, 'Fionn Lang & Anthea Lang', 'Fionn Lang', 'Anthea Lang', 2.11, 1.88);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (7, 5, 'Peter Dunne & Lillian Carthy', 'Peter Dunne', 'Lillian Carthy', 2.41, 1.54);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (8, 1, 'Lorraine Gallagher & Tina Meehan', 'Lorraine Gallagher', 'Tina Meehan', 1.59, 2.36);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (8, 2, 'Kieran Fitzpatrick & Stephen Fitzpatrick', 'Kieran Fitzpatrick', 'Stephen Fitzpatrick', 2.53, 1.27);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (8, 3, 'David O Neill & John O Neill', 'David O Neill', 'John O Neill', 1.97, 1.68);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (8, 4, 'Mark Tindale & Mark Williams', 'Mark Tindale', 'Mark Williams', 1.6, 1.98);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (8, 5, 'Kylie Maher & Seoin Talbot', 'Kylie Maher', 'Seoin Talbot', 2.28, 1.08);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (9, 1, 'Tom Foley & Fernando Souza', 'Tom Foley', 'Fernando Souza', 1.5, 1.79);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (9, 2, 'Thomas Meade & Maurice Ramsay', 'Thomas Meade', 'Maurice Ramsay', 2.6, 0.67);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (9, 3, 'Gary Stephenson & Wayne Neary', 'Gary Stephenson', 'Wayne Neary', 1.2, 2.04);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (9, 4, 'Alan Cleary & Alex Hassett', 'Alan Cleary', 'Alex Hassett', 1.23, 1.83);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (9, 5, 'Damien Dunne & Joanne Dunne', 'Damien Dunne', 'Joanne Dunne', 1.41, 1.56);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (10, 1, 'Claire Austen & CJ Adams', 'Claire Austen', 'CJ Adams', 2.31, 0.65);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (10, 2, 'Fran Ford & D M', 'Fran Ford', 'D M', 1.82, 1.14);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (10, 3, 'Niamh Cassidy & Linda Dempsey', 'Niamh Cassidy', 'Linda Dempsey', 0.95, 2.0);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (10, 4, 'Clinton Verhoog & Patrick Ffrench', 'Clinton Verhoog', 'Patrick Ffrench', 1.6, 1.31);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (10, 5, 'Felix Rothschild & Cillian Dunne', 'Felix Rothschild', 'Cillian Dunne', 1.81, 0.96);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (11, 1, 'Boodhan Rampersaud & Anto Doran', 'Boodhan Rampersaud', 'Anto Doran', 1.54, 1.22);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (11, 2, 'Nicole Mello Teixeira de Almeida & Grainne Ring', 'Nicole Mello Teixeira de Almeida', 'Grainne Ring', 1.18, 1.55);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (11, 3, 'Rick Deady & Shirley Deady', 'Rick Deady', 'Shirley Deady', 1.22, 1.4);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (11, 4, 'Michele McCormack & Sonja', 'Michele McCormack', 'Sonja', 0.98, 1.62);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (11, 5, 'Zydre & Indre Simkute', 'Zydre', 'Indre Simkute', 1.29, 1.27);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (12, 1, 'Eva Rybak & Kris Rybak', 'Eva Rybak', 'Kris Rybak', 1.27, 1.28);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (12, 2, 'Conor Dodd & Dillon Mordaunt', 'Conor Dodd', 'Dillon Mordaunt', 1.0, 1.49);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (12, 3, 'Eoin Tiernan & Eamonn Madden', 'Eoin Tiernan', 'Eamonn Madden', 1.22, 1.14);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (12, 4, 'John Lester & Kyle Dempsey', 'John Lester', 'Kyle Dempsey', 1.28, 1.05);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (12, 5, 'Katie Marie & Aoife Williams', 'Katie Marie', 'Aoife Williams', 1.1, 1.2);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (13, 1, 'Ian Donoghue & Sean Cleary', 'Ian Donoghue', 'Sean Cleary', 1.12, 1.0);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (13, 2, 'Zach Mac & John McAnulty', 'Zach Mac', 'John McAnulty', 1.23, 0.84);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (13, 3, 'Paddy Driver & Paddy Logue', 'Paddy Driver', 'Paddy Logue', 0.97, 1.04);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (13, 4, 'Gary Brady & Ciaran O''Donoghue', 'Gary Brady', 'Ciaran O''Donoghue', 0.71, 1.29);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (13, 5, 'John Martin & Alice Martin', 'John Martin', 'Alice Martin', 1.2, 0.8);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (14, 1, 'Lorna O''Rourke & Brona', 'Lorna O''Rourke', 'Brona', 0.89, 1.0);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (14, 2, 'Caragh Daly & Kerry Callery', 'Caragh Daly', 'Kerry Callery', 1.05, 0.83);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (14, 3, 'Orla Murphy Fleming & Doireann', 'Orla Murphy Fleming', 'Doireann', 1.3, 0.51);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (14, 4, 'Emily Tebbitt & Noeleen Cunningham', 'Emily Tebbitt', 'Noeleen Cunningham', 0.83, 0.94);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (14, 5, 'Sandra Dunne & Kerrie Beacom', 'Sandra Dunne', 'Kerrie Beacom', 0.66, 1.01);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (15, 1, 'Helena Plower & Olive Ramsay', 'Helena Plower', 'Olive Ramsay', 0.54, 1.11);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (15, 2, 'Jack Evans & Gavin Fogarty', 'Jack Evans', 'Gavin Fogarty', 0.83, 0.8);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (15, 3, 'Niamh Gavin & Anita Redmond', 'Niamh Gavin', 'Anita Redmond', 1.1, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (15, 4, 'Ciara Kavanagh (2) & Ciaran Conlon', 'Ciara Kavanagh (2)', 'Ciaran Conlon', 1.0, 0.56);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (15, 5, 'Elaine Kirwan & Christina Reilly', 'Elaine Kirwan', 'Christina Reilly', 1.0, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (16, 1, 'Peter O''Gara & Ross McHugh', 'Peter O''Gara', 'Ross McHugh', 0.79, 0.68);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (16, 2, 'Barry MacCourt & Michael Gombart', 'Barry MacCourt', 'Michael Gombart', 0.88, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (16, 3, 'Aoife Shine & Niall Ryan', 'Aoife Shine', 'Niall Ryan', 0.5, 0.87);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (16, 4, 'Marie Galligan & Juliette Kidd', 'Marie Galligan', 'Juliette Kidd', 0.67, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (17, 1, 'Adam Macaulay & Giedre Guobyte', 'Adam Macaulay', 'Giedre Guobyte', 0.66, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (17, 2, 'Bairbre Heron & James Heron', 'Bairbre Heron', 'James Heron', 0.5, 0.59);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (17, 3, 'John Kavanagh & Kellie Kavanagh', 'John Kavanagh', 'Kellie Kavanagh', 0.5, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (17, 4, 'Rhys Mansueto & Jeff O''Brien', 'Rhys Mansueto', 'Jeff O''Brien', 0.5, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (18, 1, 'Ken & Maria Neilan', 'Ken', 'Maria Neilan', 0.5, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (18, 2, 'Alice Gibson & Ailis T', 'Alice Gibson', 'Ailis T', 0.5, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (18, 3, 'Keith Taurai & Conor McMahon', 'Keith Taurai', 'Conor McMahon', 0.5, 0.5);
insert into public.box_teams (box, seed, name, p1, p2, r1, r2) values (18, 4, 'Pravin Kaware & Yashvardhan Singh Rathore', 'Pravin Kaware', 'Yashvardhan Singh Rathore', 0.5, 0.5);
commit;

-- ── PART 1: team contact emails — 160 of 174 players matched to a Playtomic account ──
-- Joined by team name, so this survives the reinsert above.
insert into public.box_team_contacts (team_id, email)
select id, 'swdonoh@gmail.com' from public.box_teams where name = 'Shane Donohoe & Dylan Orr'  -- Shane Donohoe (by name)
union all select id, 'dylanorr7@gmail.com' from public.box_teams where name = 'Shane Donohoe & Dylan Orr'  -- Dylan Orr (by name)
union all select id, 'david.osullivan658@gmail.com' from public.box_teams where name = 'Davy O''Sullivan & David Hennebry'  -- Davy O''Sullivan (by name)
union all select id, 'davidmhennebry7@gmail.com' from public.box_teams where name = 'Davy O''Sullivan & David Hennebry'  -- David Hennebry (by name)
union all select id, 'jpftcomerford@gmail.com' from public.box_teams where name = 'J.P. Comerford & Conor Ruttledge'  -- J.P. Comerford (by name)
union all select id, 'booms86@gmail.com' from public.box_teams where name = 'J.P. Comerford & Conor Ruttledge'  -- Conor Ruttledge (by name)
union all select id, 'tomas.morrissey@gmail.com' from public.box_teams where name = 'Tomas Morrissey & Brian Cornyn'  -- Tomas Morrissey (by name)
union all select id, 'briancornyn44@gmail.com' from public.box_teams where name = 'Tomas Morrissey & Brian Cornyn'  -- Brian Cornyn (by name)
union all select id, 'daviddeady89@gmail.com' from public.box_teams where name = 'David Deady & Rob Lucy'  -- David Deady (by name)
union all select id, 'roblucy7@gmail.com' from public.box_teams where name = 'David Deady & Rob Lucy'  -- Rob Lucy (by name)
union all select id, 'jamesconnolly1@live.ie' from public.box_teams where name = 'James Connolly & Michael Connolly'  -- James Connolly (by name)
union all select id, 'mikemaxshanahan@gmail.com' from public.box_teams where name = 'Mike Shanahan & Greg Shine'  -- Mike Shanahan (by name)
union all select id, 'me@gregshine.com' from public.box_teams where name = 'Mike Shanahan & Greg Shine'  -- Greg Shine (by name)
union all select id, 'deannoble106@gmail.com' from public.box_teams where name = 'Dean Noble & Chris Ffrench'  -- Dean Noble (by name)
union all select id, 'chrisffrench.cf@gmail.com' from public.box_teams where name = 'Dean Noble & Chris Ffrench'  -- Chris Ffrench (by name)
union all select id, 'dylanfurlong265@gmail.com' from public.box_teams where name = 'Dylan Furlong & Jack Furlong'  -- Dylan Furlong (by name)
union all select id, 'furlongjack1@gmail.com' from public.box_teams where name = 'Dylan Furlong & Jack Furlong'  -- Jack Furlong (by name)
union all select id, 'antonio.loboschi@gmail.com' from public.box_teams where name = 'Antonio Loboschi & Sahil Kaistha'  -- Antonio Loboschi (by name)
union all select id, 'cssahilkaistha@gmail.com' from public.box_teams where name = 'Antonio Loboschi & Sahil Kaistha'  -- Sahil Kaistha (by name)
union all select id, 'mattcullen11@hotmail.com' from public.box_teams where name = 'Matthew & Nathan Condell'  -- Matthew (by name)
union all select id, 'nathancondell1992@gmail.com' from public.box_teams where name = 'Matthew & Nathan Condell'  -- Nathan Condell (by name)
union all select id, 'seanleonard01@outlook.com' from public.box_teams where name = 'Sean Leonard & Dylan Frazer'  -- Sean Leonard (by name)
union all select id, '13dfraze@gmail.com' from public.box_teams where name = 'Sean Leonard & Dylan Frazer'  -- Dylan Frazer (by name)
union all select id, 'ingvard14@gmail.com' from public.box_teams where name = 'Ingvard Hanssen & Oisin Breen'  -- Ingvard Hanssen (by name)
union all select id, 'oisinbreen@gmail.com' from public.box_teams where name = 'Ingvard Hanssen & Oisin Breen'  -- Oisin Breen (by name)
union all select id, 'dgwwtqj76q@privaterelay.appleid.com' from public.box_teams where name = 'Ciara Kavanagh & Rory Fahey'  -- Ciara Kavanagh (by rating)
union all select id, 'rubmail4me@gmail.com' from public.box_teams where name = 'Ciara Kavanagh & Rory Fahey'  -- Rory Fahey (by name)
union all select id, 'dawn.beas@gmail.com' from public.box_teams where name = 'Ronel Pickford & Dawn B'  -- Dawn B (by name)
union all select id, 'dm@desmartin.io' from public.box_teams where name = 'Desmond Martin & Dave Smyth'  -- Desmond Martin (by name)
union all select id, 'devshane99@gmail.com' from public.box_teams where name = 'Shane Devlin & Karl Earls'  -- Shane Devlin (by name)
union all select id, 'karlearls@hotmail.com' from public.box_teams where name = 'Shane Devlin & Karl Earls'  -- Karl Earls (by name)
union all select id, 'markbanim@gmail.com' from public.box_teams where name = 'Mark Banim & Anton Burihhin'  -- Mark Banim (by name)
union all select id, 'burihhin@icloud.com' from public.box_teams where name = 'Mark Banim & Anton Burihhin'  -- Anton Burihhin (by name)
union all select id, 'kfraser@tcd.ie' from public.box_teams where name = 'Kieran Fraser & Ana J'  -- Kieran Fraser (by name)
union all select id, 'anajimezg@gmail.com' from public.box_teams where name = 'Kieran Fraser & Ana J'  -- Ana J (by name)
union all select id, 'shaun.humby@gmail.com' from public.box_teams where name = 'Shaun Humby & Thomas McKeon'  -- Shaun Humby (by name)
union all select id, 'thomasmckeon1997@gmail.com' from public.box_teams where name = 'Shaun Humby & Thomas McKeon'  -- Thomas McKeon (by name)
union all select id, 'tommaguire21@gmail.com' from public.box_teams where name = 'Tom Maguire & Brian O''Sullivan'  -- Tom Maguire (by name)
union all select id, 'mr.osullivan@holyrosaryschool.ie' from public.box_teams where name = 'Tom Maguire & Brian O''Sullivan'  -- Brian O''Sullivan (by name)
union all select id, 'lee@rosannaconstruction.ie' from public.box_teams where name = 'Lee Fitzpatrick & Mo Dunne'  -- Lee Fitzpatrick (by name)
union all select id, 'momodunner9@gmail.com' from public.box_teams where name = 'Lee Fitzpatrick & Mo Dunne'  -- Mo Dunne (by name)
union all select id, 'kaysully97@gmail.com' from public.box_teams where name = 'Kayleigh Sullivan & Leanne S'  -- Kayleigh Sullivan (by name)
union all select id, 'lasully1017@gmail.com' from public.box_teams where name = 'Kayleigh Sullivan & Leanne S'  -- Leanne S (by name)
union all select id, 'aisling1983@gmail.com' from public.box_teams where name = 'Aisling O''Brien & Patrick Kennelly'  -- Aisling O''Brien (by name)
union all select id, 'patrickkennelly83@gmail.com' from public.box_teams where name = 'Aisling O''Brien & Patrick Kennelly'  -- Patrick Kennelly (by name)
union all select id, 'cmlee191@gmail.com' from public.box_teams where name = 'Charles Lee & Cami Ammirevole'  -- Charles Lee (by name)
union all select id, '56gstz8rp6@privaterelay.appleid.com' from public.box_teams where name = 'Karol Stankiewicz & Sath'  -- Karol Stankiewicz (by name)
union all select id, 'sathrajith2022@gmail.com' from public.box_teams where name = 'Karol Stankiewicz & Sath'  -- Sath (by name)
union all select id, 'itto@protonmail.ch' from public.box_teams where name = 'Gabriel Uribe & Aron Souto'  -- Gabriel Uribe (by name)
union all select id, 'asouto244@gmail.com' from public.box_teams where name = 'Gabriel Uribe & Aron Souto'  -- Aron Souto (by name)
union all select id, 'callumsmale10@gmail.com' from public.box_teams where name = 'Callum Smale & Ryan Tolan'  -- Callum Smale (by name)
union all select id, 'ryantolanchr@gmail.com' from public.box_teams where name = 'Callum Smale & Ryan Tolan'  -- Ryan Tolan (by name)
union all select id, 'cillian.w191@gmail.com' from public.box_teams where name = 'Cillian Williams & Ava Williams'  -- Cillian Williams (by name)
union all select id, 'wava16@icloud.com' from public.box_teams where name = 'Cillian Williams & Ava Williams'  -- Ava Williams (by name)
union all select id, 'chris@squirrelsscramble.ie' from public.box_teams where name = 'Keefe Lang & Chris Lang'  -- Chris Lang (by name)
union all select id, 'johndaly0064@gmail.com' from public.box_teams where name = 'John D & Sam Harte'  -- John D (by name)
union all select id, 'samharte@ymail.com' from public.box_teams where name = 'John D & Sam Harte'  -- Sam Harte (by name)
union all select id, 'toby_wuyts@hotmail.co.uk' from public.box_teams where name = 'Toby Wuyts & Jack Dunn'  -- Toby Wuyts (by name)
union all select id, 'dunnj015@gmail.com' from public.box_teams where name = 'Toby Wuyts & Jack Dunn'  -- Jack Dunn (by name)
union all select id, 'oussama.milahaa@gmail.com' from public.box_teams where name = 'Oussama Kenouche & Jack Colaluca'  -- Oussama Kenouche (by name)
union all select id, 'jackcolaluca1@icloud.com' from public.box_teams where name = 'Oussama Kenouche & Jack Colaluca'  -- Jack Colaluca (by name)
union all select id, 'filang@outlook.ie' from public.box_teams where name = 'Fionn Lang & Anthea Lang'  -- Fionn Lang (by name)
union all select id, 'abeattie77@gmail.com' from public.box_teams where name = 'Fionn Lang & Anthea Lang'  -- Anthea Lang (by name)
union all select id, 'p.dunne@holyrosaryschool.ie' from public.box_teams where name = 'Peter Dunne & Lillian Carthy'  -- Peter Dunne (by name)
union all select id, 'lilliancarthy@hotmail.com' from public.box_teams where name = 'Peter Dunne & Lillian Carthy'  -- Lillian Carthy (by name)
union all select id, 'lorrainegwicklow@gmail.com' from public.box_teams where name = 'Lorraine Gallagher & Tina Meehan'  -- Lorraine Gallagher (by rating)
union all select id, 'tinaphysio1@gmail.com' from public.box_teams where name = 'Lorraine Gallagher & Tina Meehan'  -- Tina Meehan (by name)
union all select id, 'kieranfitz03@gmail.com' from public.box_teams where name = 'Kieran Fitzpatrick & Stephen Fitzpatrick'  -- Kieran Fitzpatrick (by name)
union all select id, 'stephenmfitzpatrick@hotmail.com' from public.box_teams where name = 'Kieran Fitzpatrick & Stephen Fitzpatrick'  -- Stephen Fitzpatrick (by name)
union all select id, 'dylanoneill0909@gmail.com' from public.box_teams where name = 'David O Neill & John O Neill'  -- David O Neill (by name)
union all select id, 'naileroneill80@gmail.com' from public.box_teams where name = 'David O Neill & John O Neill'  -- John O Neill (by name)
union all select id, 'metindale@gmail.com' from public.box_teams where name = 'Mark Tindale & Mark Williams'  -- Mark Tindale (by name)
union all select id, 'msg8f59z7p@privaterelay.appleid.com' from public.box_teams where name = 'Mark Tindale & Mark Williams'  -- Mark Williams (by name)
union all select id, 'myliekaher@gmail.com' from public.box_teams where name = 'Kylie Maher & Seoin Talbot'  -- Kylie Maher (by name)
union all select id, 'seointalbot@gmail.com' from public.box_teams where name = 'Kylie Maher & Seoin Talbot'  -- Seoin Talbot (by name)
union all select id, 'tomfoley55@gmail.com' from public.box_teams where name = 'Tom Foley & Fernando Souza'  -- Tom Foley (by name)
union all select id, '7hmm2tv628@privaterelay.appleid.com' from public.box_teams where name = 'Tom Foley & Fernando Souza'  -- Fernando Souza (by name)
union all select id, 'thomasmeade08@gmail.com' from public.box_teams where name = 'Thomas Meade & Maurice Ramsay'  -- Thomas Meade (by name)
union all select id, 'mramsay2912@gmail.com' from public.box_teams where name = 'Thomas Meade & Maurice Ramsay'  -- Maurice Ramsay (by name)
union all select id, 'gjgstephenson@yahoo.ie' from public.box_teams where name = 'Gary Stephenson & Wayne Neary'  -- Gary Stephenson (by name)
union all select id, 'wayneneary1979@gmail.com' from public.box_teams where name = 'Gary Stephenson & Wayne Neary'  -- Wayne Neary (by name)
union all select id, 'alan4cleary@gmail.com' from public.box_teams where name = 'Alan Cleary & Alex Hassett'  -- Alan Cleary (by name)
union all select id, 'hassettwex@gmail.com' from public.box_teams where name = 'Alan Cleary & Alex Hassett'  -- Alex Hassett (by name)
union all select id, 'cassidyniamh@gmail.com' from public.box_teams where name = 'Niamh Cassidy & Linda Dempsey'  -- Niamh Cassidy (by name)
union all select id, 'lindadempseyred@gmail.com' from public.box_teams where name = 'Niamh Cassidy & Linda Dempsey'  -- Linda Dempsey (by name)
union all select id, 'eclairejausten@gmail.com' from public.box_teams where name = 'Claire Austen & CJ Adams'  -- Claire Austen (by name)
union all select id, 'franford2007@hotmail.com' from public.box_teams where name = 'Fran Ford & D M'  -- Fran Ford (by name)
union all select id, 'durwyn.mongey@gmail.com' from public.box_teams where name = 'Fran Ford & D M'  -- D M (by name)
union all select id, 'damien.dunne4@gmail.com' from public.box_teams where name = 'Damien Dunne & Joanne Dunne'  -- Damien Dunne (by name)
union all select id, 'jplunkettdunne@gmail.com' from public.box_teams where name = 'Damien Dunne & Joanne Dunne'  -- Joanne Dunne (by name)
union all select id, 'clintonverhoog@gmail.com' from public.box_teams where name = 'Clinton Verhoog & Patrick Ffrench'  -- Clinton Verhoog (by name)
union all select id, 'pat.ffrench@outlook.com' from public.box_teams where name = 'Clinton Verhoog & Patrick Ffrench'  -- Patrick Ffrench (by name)
union all select id, 'felixrothschild09@gmail.com' from public.box_teams where name = 'Felix Rothschild & Cillian Dunne'  -- Felix Rothschild (by name)
union all select id, 'zdqrdrfh8k@privaterelay.appleid.com' from public.box_teams where name = 'Felix Rothschild & Cillian Dunne'  -- Cillian Dunne (by name)
union all select id, 'boodhanrampersaud@gmail.com' from public.box_teams where name = 'Boodhan Rampersaud & Anto Doran'  -- Boodhan Rampersaud (by name)
union all select id, 'anthonydoran88@gmail.com' from public.box_teams where name = 'Boodhan Rampersaud & Anto Doran'  -- Anto Doran (by name)
union all select id, 'nikimello@hotmail.com' from public.box_teams where name = 'Nicole Mello Teixeira de Almeida & Grainne Ring'  -- Nicole Mello Teixeira de Almeida (by rating)
union all select id, 'graring@gmail.com' from public.box_teams where name = 'Nicole Mello Teixeira de Almeida & Grainne Ring'  -- Grainne Ring (by rating)
union all select id, 'ddrick25@gmail.com' from public.box_teams where name = 'Rick Deady & Shirley Deady'  -- Rick Deady (by name)
union all select id, 'ddshir2025@gmail.com' from public.box_teams where name = 'Rick Deady & Shirley Deady'  -- Shirley Deady (by name)
union all select id, 'shelly_mccormack@hotmail.com' from public.box_teams where name = 'Michele McCormack & Sonja'  -- Michele McCormack (by name)
union all select id, 'sonja.dorlas94@gmail.com' from public.box_teams where name = 'Michele McCormack & Sonja'  -- Sonja (by name)
union all select id, 'zydre.guo@gmail.com' from public.box_teams where name = 'Zydre & Indre Simkute'  -- Zydre (by name)
union all select id, 'indreslaiskas@gmail.com' from public.box_teams where name = 'Zydre & Indre Simkute'  -- Indre Simkute (by name)
union all select id, 'ewarybak81@gmail.com' from public.box_teams where name = 'Eva Rybak & Kris Rybak'  -- Eva Rybak (by name)
union all select id, 'kris30garage@gmail.com' from public.box_teams where name = 'Eva Rybak & Kris Rybak'  -- Kris Rybak (by name)
union all select id, 'conordodd98@gmail.com' from public.box_teams where name = 'Conor Dodd & Dillon Mordaunt'  -- Conor Dodd (by name)
union all select id, 'mordauntdillon@gmail.com' from public.box_teams where name = 'Conor Dodd & Dillon Mordaunt'  -- Dillon Mordaunt (by name)
union all select id, 'q9rgxnfphk@privaterelay.appleid.com' from public.box_teams where name = 'Eoin Tiernan & Eamonn Madden'  -- Eoin Tiernan (by name)
union all select id, 'eamonnmadden@hotmail.com' from public.box_teams where name = 'Eoin Tiernan & Eamonn Madden'  -- Eamonn Madden (by name)
union all select id, 'johnlester18@gmail.com' from public.box_teams where name = 'John Lester & Kyle Dempsey'  -- John Lester (by name)
union all select id, 'katiemarie1968@gmail.com' from public.box_teams where name = 'Katie Marie & Aoife Williams'  -- Katie Marie (by name)
union all select id, 'aoifewilliams7@gmail.com' from public.box_teams where name = 'Katie Marie & Aoife Williams'  -- Aoife Williams (by name)
union all select id, 'iandonoghue77@gmail.com' from public.box_teams where name = 'Ian Donoghue & Sean Cleary'  -- Ian Donoghue (by name)
union all select id, 'seanclearyj@gmail.com' from public.box_teams where name = 'Ian Donoghue & Sean Cleary'  -- Sean Cleary (by name)
union all select id, 'zachjackmac@gmail.com' from public.box_teams where name = 'Zach Mac & John McAnulty'  -- Zach Mac (by name)
union all select id, 'jwmcanulty@gmail.com' from public.box_teams where name = 'Zach Mac & John McAnulty'  -- John McAnulty (by name)
union all select id, 'garybrady10@hotmail.com' from public.box_teams where name = 'Gary Brady & Ciaran O''Donoghue'  -- Gary Brady (by name)
union all select id, 'dunnington1989@gmail.com' from public.box_teams where name = 'Gary Brady & Ciaran O''Donoghue'  -- Ciaran O''Donoghue (by name)
union all select id, 'john@renova.ie' from public.box_teams where name = 'John Martin & Alice Martin'  -- John Martin (by name)
union all select id, 'alicehayman@gmail.com' from public.box_teams where name = 'John Martin & Alice Martin'  -- Alice Martin (by name)
union all select id, 'nigeldriver81@gmail.com' from public.box_teams where name = 'Paddy Driver & Paddy Logue'  -- Paddy Driver (by name)
union all select id, 'jwyyv9nn8t@privaterelay.appleid.com' from public.box_teams where name = 'Paddy Driver & Paddy Logue'  -- Paddy Logue (by name)
union all select id, 'lornaor1984@gmail.com' from public.box_teams where name = 'Lorna O''Rourke & Brona'  -- Lorna O''Rourke (by name)
union all select id, 'bronasutton@gmail.com' from public.box_teams where name = 'Lorna O''Rourke & Brona'  -- Brona (by name)
union all select id, 'caraghd@gmail.com' from public.box_teams where name = 'Caragh Daly & Kerry Callery'  -- Caragh Daly (by name+rating)
union all select id, 'niallandkerry@gmail.com' from public.box_teams where name = 'Caragh Daly & Kerry Callery'  -- Kerry Callery (by name)
union all select id, 'orlatmurphy@icloud.com' from public.box_teams where name = 'Orla Murphy Fleming & Doireann'  -- Orla Murphy Fleming (by name)
union all select id, 'doireannennis@yahoo.com' from public.box_teams where name = 'Orla Murphy Fleming & Doireann'  -- Doireann (by name)
union all select id, 'emily.tebbitt@gmail.com' from public.box_teams where name = 'Emily Tebbitt & Noeleen Cunningham'  -- Emily Tebbitt (by name)
union all select id, 'noeleen.cunningham@gmail.com' from public.box_teams where name = 'Emily Tebbitt & Noeleen Cunningham'  -- Noeleen Cunningham (by name)
union all select id, 'barrymaccourt@gmail.com' from public.box_teams where name = 'Barry MacCourt & Michael Gombart'  -- Barry MacCourt (by rating)
union all select id, 'sandradunne75@gmail.com' from public.box_teams where name = 'Sandra Dunne & Kerrie Beacom'  -- Sandra Dunne (by name)
union all select id, 'kerriegbeacom@yahoo.ie' from public.box_teams where name = 'Sandra Dunne & Kerrie Beacom'  -- Kerrie Beacom (by name)
union all select id, 'helenaplower@gmail.com' from public.box_teams where name = 'Helena Plower & Olive Ramsay'  -- Helena Plower (by name)
union all select id, 'thgh45vffr@privaterelay.appleid.com' from public.box_teams where name = 'Helena Plower & Olive Ramsay'  -- Olive Ramsay (by name)
union all select id, 'jacklucasevans@gmail.com' from public.box_teams where name = 'Jack Evans & Gavin Fogarty'  -- Jack Evans (by name)
union all select id, 'gavinfogarty1501@gmail.com' from public.box_teams where name = 'Jack Evans & Gavin Fogarty'  -- Gavin Fogarty (by name)
union all select id, 'niamh.otooleabc@gmail.com' from public.box_teams where name = 'Niamh Gavin & Anita Redmond'  -- Niamh Gavin (by name)
union all select id, 'anita.redmond1@gmail.com' from public.box_teams where name = 'Niamh Gavin & Anita Redmond'  -- Anita Redmond (by name)
union all select id, 'kavanaghciara@gmail.com' from public.box_teams where name = 'Ciara Kavanagh (2) & Ciaran Conlon'  -- Ciara Kavanagh (2) (by rating)
union all select id, 'yg6jw48g4y@privaterelay.appleid.com' from public.box_teams where name = 'Ciara Kavanagh (2) & Ciaran Conlon'  -- Ciaran Conlon (by name)
union all select id, 'elaine.kirwan3@gmail.com' from public.box_teams where name = 'Elaine Kirwan & Christina Reilly'  -- Elaine Kirwan (by name)
union all select id, 'christinamaryreilly@gmail.com' from public.box_teams where name = 'Elaine Kirwan & Christina Reilly'  -- Christina Reilly (by name)
union all select id, 'rossmchugh@gmail.com' from public.box_teams where name = 'Peter O''Gara & Ross McHugh'  -- Ross McHugh (by name)
union all select id, 'shineaoife@gmail.com' from public.box_teams where name = 'Aoife Shine & Niall Ryan'  -- Aoife Shine (by name)
union all select id, 'nryanie@gmail.com' from public.box_teams where name = 'Aoife Shine & Niall Ryan'  -- Niall Ryan (by name)
union all select id, 'adamaca@gmail.com' from public.box_teams where name = 'Adam Macaulay & Giedre Guobyte'  -- Adam Macaulay (by name)
union all select id, 'giedrike@gmail.com' from public.box_teams where name = 'Adam Macaulay & Giedre Guobyte'  -- Giedre Guobyte (by name)
union all select id, 'marieinwicklow@gmail.com' from public.box_teams where name = 'Marie Galligan & Juliette Kidd'  -- Marie Galligan (by name)
union all select id, 'jujujjkidd05@gmail.com' from public.box_teams where name = 'Marie Galligan & Juliette Kidd'  -- Juliette Kidd (by name)
union all select id, 'bairbreheron@gmail.com' from public.box_teams where name = 'Bairbre Heron & James Heron'  -- Bairbre Heron (by name)
union all select id, 'jamesheron2010@gmail.com' from public.box_teams where name = 'Bairbre Heron & James Heron'  -- James Heron (by name)
union all select id, 'kavanaghjo@gmail.com' from public.box_teams where name = 'John Kavanagh & Kellie Kavanagh'  -- John Kavanagh (by name)
union all select id, 'kellie.kavanagh@gmail.com' from public.box_teams where name = 'John Kavanagh & Kellie Kavanagh'  -- Kellie Kavanagh (by name)
union all select id, 'jeffrey.j.obrien@gmail.com' from public.box_teams where name = 'Rhys Mansueto & Jeff O''Brien'  -- Jeff O''Brien (by name)
union all select id, 'strangedays@duck.com' from public.box_teams where name = 'Ken & Maria Neilan'  -- Ken (by name)
union all select id, 'neilanmaria@gmail.com' from public.box_teams where name = 'Ken & Maria Neilan'  -- Maria Neilan (by name)
union all select id, 'tauraik@tcd.ie' from public.box_teams where name = 'Keith Taurai & Conor McMahon'  -- Keith Taurai (by name)
union all select id, 'condor26@gmail.com' from public.box_teams where name = 'Keith Taurai & Conor McMahon'  -- Conor McMahon (by name)
on conflict do nothing;

-- Unmatched players (14) — add by hand when their email is known:
--   insert into public.box_team_contacts (team_id, email) select id, '<email>' from public.box_teams where name = '<Team name>';
--   Michael Connolly  (no account under this name)
--   Ronel Pickford  (no account under this name)
--   Dave Smyth  (no account under this name)
--   Cami Ammirevole  (no account under this name)
--   Keefe Lang  (no account under this name)
--   CJ Adams  (no account under this name)
--   Kyle Dempsey  (no account under this name)
--   Michael Gombart  (no account under this name)
--   Peter O'Gara  (no account under this name)
--   Rhys Mansueto  (no account under this name)
--   Alice Gibson  (no account under this name)
--   Ailis T  (no account under this name)
--   Pravin Kaware  (no account under this name)
--   Yashvardhan Singh Rathore  (no account under this name)

-- TEAMS WITH NO CONTACT AT ALL (2) — these cannot submit or confirm until an email is added:
--   !! Alice Gibson & Ailis T
--   !! Pravin Kaware & Yashvardhan Singh Rathore

-- ── PART 2: cycle-1 fixtures (all-play-all within each box; idempotent) ──
insert into public.box_matches (box, cycle, team1_id, team2_id)
select a.box, 1, a.id, b.id from public.box_teams a join public.box_teams b on b.box = a.box and b.active and a.seed < b.seed
where a.active on conflict (cycle, team1_id, team2_id) do nothing;

-- ── PART 3: TEST FIXTURE for the self-serve entry (box 99, two dummy teams, one match) ──
insert into public.box_teams (box, seed, name, p1, p2, r1, r2, active) values
  (99, 1, 'TEST Team A', 'Test Alpha', 'Test Aoife', 2.0, 2.0, true),
  (99, 2, 'TEST Team B', 'Test Bravo', 'Test Brid', 2.0, 2.0, true)
on conflict (box, seed) do nothing;
insert into public.box_team_contacts (team_id, email)
select id, 'richiecarroll65+boxa@gmail.com' from public.box_teams where box = 99 and seed = 1
union all select id, 'richiecarroll65+boxb@gmail.com' from public.box_teams where box = 99 and seed = 2
on conflict do nothing;
insert into public.box_matches (box, cycle, team1_id, team2_id)
select 99, 1, a.id, b.id from public.box_teams a, public.box_teams b where a.box = 99 and a.seed = 1 and b.box = 99 and b.seed = 2
on conflict (cycle, team1_id, team2_id) do nothing;

-- ── CLEANUP after the test ──
-- delete from public.box_teams where box = 99;
